ARG DEV_IMAGE_TAG=ai-dome-dev
FROM ${DEV_IMAGE_TAG}

RUN npm install -g opencode-ai@latest && \
    npm cache clean --force

USER ai-dome
RUN ln -sf /home/ai-dome/project/.gitconfig /home/ai-dome/.gitconfig
WORKDIR /home/ai-dome/project
